# escape timeout in neovim
set -sg escape-time 0

# Setting up colors
# https://gist.github.com/ziimir/e5599c003b1431500117126d7b095368
set -g default-terminal 'screen-256color'
set -as terminal-overrides ',alacritty*:Tc'

# Reload tmux config so we can pick up changes to this file without needing to restart tmux
bind r source-file ~/.tmux.conf \; display "Reloaded tmux configuration!"

# Use vi-style navigation in Copy mode (which is also scrollback mode)
setw -g mode-keys vi
bind v copy-mode # Войти в visual/copy mode
bind -T copy-mode-vi v send-keys -X begin-selection # Начать обычное выделение
bind -T copy-mode-vi V send-keys -X select-line # Выделить строки целиком
bind -T copy-mode-vi y send-keys -X copy-selection-and-cancel # Скопировать и выйти
bind -T copy-mode-vi Escape send-keys -X cancel # Escape отменяет выделение или выходит
set -s copy-command 'pbcopy' # Копирование в системный clipboard

# Setting up status line messages are displaing
set -g display-time 3000

# Navigate panes vim-style!
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# New panes in same directory
bind '%' split-window -h -c '#{pane_current_path}'  # Split panes horizontal
bind '"' split-window -v -c '#{pane_current_path}'  # Split panes vertically

# New windows in same directory
bind C new-window -c "#{pane_current_path}"

# Start windows and panes at 1, not 0
set -g base-index 1
setw -g pane-base-index 1

# Pane title
set -g pane-border-status off
#set -g pane-border-format ' #{pane_title} | #{s|^#{E:HOME}|~|:pane_current_path} | #{pane_current_command} '
set -g pane-border-format '#{?pane_active,\
 #{pane_title} | #{s|^#{E:HOME}|~|:pane_current_path} | #{pane_current_command} ,\
 #{pane_title} | #{pane_current_command} \
}'
bind T command-prompt -p "Pane name:" "select-pane -T '%%'"
set -g pane-active-border-style 'fg=yellow'
set -g pane-border-style 'fg=white'
set -g pane-border-lines heavy

# Stacking panes
bind S if-shell -F '#{==:#{@stacking_mode},1}' {
    set-option -w @stacking_mode 0
    select-layout even-vertical
} {
    if-shell -F '#{>:#{window_panes},1}' {
        set-option -w @stacking_mode 1
        run-shell '~/.local/bin/tmux-stack-panes.sh'
    }
}
set-hook -g after-select-pane {
    if-shell -F '#{==:#{@stacking_mode},1}' {
        run-shell '~/.local/bin/tmux-stack-panes.sh'
    }
}
set-hook -g window-layout-changed { # хук на изменение геометрии window
    if-shell -F '#{==:#{window_panes},1}' {
        set-option -w @stacking_mode 0 # выключаем stacking mode
        set-option -w pane-border-status off # выключаем title у pane
    } {
        set-option -w pane-border-status top # включаем title у pane
    }
}

# Resizing panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 5

# And windows too!
bind -r C-l select-window -t :+
bind -r C-h select-window -t :-

# Windows highlighting in status line
setw -g window-status-format "#I:#{b:pane_current_path}"
setw -g window-status-style fg=black,bg=green

setw -g window-status-last-style fg=black,bg=green
setw -g window-status-bell-style fg=black,bg=green
setw -g window-status-activity-style fg=black,bg=green

setw -g window-status-current-style fg=green,bg=black
set -g window-status-current-format '#I#{?#{==:#{@stacking_mode},1},:#[fg=yellow],}#[default]:#{b:pane_current_path}'

# Monitor windows for activity
setw -g monitor-activity on
set -g visual-activity on

# Status bar
set -g status-right '#(test -n "$SSH_CONNECTION" && printf "#[bg=red] [#h] " || printf "")'
set -g status-position top
set -g status-left-length 100
set -g status-interval 15

# Sessions in popup
bind s display-popup \
    -E \
    -w 80% \
    -h 80% \
    -T " Current: #S " \
    "tmux list-sessions | sed -E 's/:.*$//' | grep -v \"^$(tmux display-message -p '#S')\$\" | fzf --reverse | xargs tmux switch-client -t"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
run '~/.tmux/plugins/tpm/tpm'
