[[manager.prepend_keymap]]
on   = "<C-s>"
run  = 'shell "$SHELL" --block --confirm'
desc = "Open shell here"

[[manager.prepend_keymap]]
on   = "<C-t>"
run  = 'plugin --sync test'
desc = "Open shell here"
